// =============================================================================
// email.ts — Server-only. Never import from Client Components.
//
// Thin wrapper around the Resend API.
// Credentials come exclusively from server-side environment variables:
//   RESEND_API_KEY    — your Resend API key (re_xxxxxxxxxxxx)
//   RESEND_FROM_EMAIL — the verified sender address (e.g. no-reply@niyaro.in)
//
// The OTP code is generated by the caller and passed in — this module never
// generates or logs codes.
// =============================================================================

import { Resend } from "resend"

function getResend(): Resend {
  const key = process.env.RESEND_API_KEY
  if (!key) throw new Error("RESEND_API_KEY is not set")
  return new Resend(key)
}

function getFromEmail(): string {
  return process.env.RESEND_FROM_EMAIL ?? "no-reply@niyaroindia.vercel.app"
}

export interface SendPasswordResetOptions {
  toEmail:     string
  toName:      string
  code:        string   // the plaintext 6-digit code — only ever sent to the
                        // recipient's inbox, never stored here
}

/**
 * Sends a password-reset verification code email.
 * Throws if the Resend API call fails, so the caller can surface a generic
 * error to the customer without leaking internal details.
 */
export async function sendPasswordResetEmail({
  toEmail,
  toName,
  code,
}: SendPasswordResetOptions): Promise<void> {
  const resend = getResend()
  const from   = getFromEmail()

  const { error } = await resend.emails.send({
    from,
    to:      toEmail,
    subject: "Reset your NIYARO password",
    html:    buildHtml(toName, code),
    text:    buildText(toName, code),
  })

  if (error) {
    // Log only a sanitised message — never log the code or API key
    console.error("[email] Failed to send password reset email:", error.message)
    throw new Error("Failed to send email. Please try again.")
  }
}

// ─── Email templates ──────────────────────────────────────────────────────────

function buildText(name: string, code: string): string {
  return [
    `Hello ${name},`,
    "",
    "We received a request to reset your NIYARO account password.",
    "",
    `Your verification code is:  ${code}`,
    "",
    "This code expires in 10 minutes.",
    "",
    "If you did not request this, you can safely ignore this email.",
    "",
    "Regards,",
    "NIYARO",
  ].join("\n")
}

function buildHtml(name: string, code: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reset your NIYARO password</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px;">
    <tr>
      <td align="center">
        <table width="100%" style="max-width:520px;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);">
          <!-- Header -->
          <tr>
            <td style="background:#1e1b4b;padding:28px 32px;">
              <p style="margin:0;font-size:22px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;">
                🧵 NIYARO
              </p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:36px 32px 28px;">
              <p style="margin:0 0 8px;font-size:20px;font-weight:700;color:#111827;">
                Reset your password
              </p>
              <p style="margin:0 0 24px;font-size:15px;color:#6b7280;line-height:1.6;">
                Hello ${escapeHtml(name)},<br />
                We received a request to reset your NIYARO account password. Use the code below to continue.
              </p>

              <!-- OTP block -->
              <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:24px;text-align:center;margin-bottom:24px;">
                <p style="margin:0 0 6px;font-size:12px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:#9ca3af;">
                  Verification Code
                </p>
                <p style="margin:0;font-size:40px;font-weight:800;letter-spacing:.2em;color:#1e1b4b;font-family:'Courier New',monospace;">
                  ${escapeHtml(code)}
                </p>
                <p style="margin:10px 0 0;font-size:12px;color:#9ca3af;">
                  Expires in 10 minutes
                </p>
              </div>

              <p style="margin:0;font-size:13px;color:#9ca3af;line-height:1.6;">
                If you did not request a password reset, you can safely ignore this email.
                Your account will remain secure.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:20px 32px;">
              <p style="margin:0;font-size:12px;color:#9ca3af;text-align:center;">
                &copy; NIYARO &mdash; Textile Commerce
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;")
}
